#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be:
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

testcases = int(input())
tests = []

for i in range (testcases):
    x = input('')  #amount of test cases
    tests.append(i)

def Fibonacci():
    for i in range(testcases):
        